/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daftarmahasiswa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private Boolean isUpdate = false;
    private int selectedID = -1;
    private ArrayList<Mahasiswa> listMhs;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        listMhs = new ArrayList<>();
        //Dummy
        listMhs.add(new Mahasiswa("1111", "Aaaa", "A","XXXX"));
        listMhs.add(new Mahasiswa("2222", "Bbbb", "B","YYYY"));
        listMhs.add(new Mahasiswa("3333", "Cccc", "C","ZZZZ"));
        // Set Table
        jTable1.setModel(setTable());
        // Hide Delete button
        jTombolDelete.setVisible(false);
    }

    public final DefaultTableModel setTable() {
        Object[] column = {"NIM", "Nama", "Nilai", "Gender"};
        DefaultTableModel dataTabel = new DefaultTableModel(null, column);
        for (int i = 0; i < listMhs.size(); i++) {
            Object[] row = new Object[4];
            row[0] = listMhs.get(i).getNim();
            row[1] = listMhs.get(i).getNama();
            row[2] = listMhs.get(i).getNilai();
            row[3] = listMhs.get(i).getGender();
            dataTabel.addRow(row);
        }
        return dataTabel;
    }

    public void insertData() {
        // Get Data
        String nim = jFieldNIM.getText();
        String nama = jFieldNama.getText();
        String nilai = jFieldNilai.getText();
        String gender = "";
        if(btLaki.isSelected()==true){
            gender = btLaki.getText();
        }else if(btPerempuan.isSelected()==true) {
            gender = btPerempuan.getText();
        }

        listMhs.add(new Mahasiswa(nim, nama, nilai, gender));
        
        //Update Table
        jTable1.setModel(setTable());

        System.out.println("Insert Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");
        
        //reset form         
        resetForm();
    }

    public void updateData() {
        // Get Data
        String nim = jFieldNIM.getText();
        String nama = jFieldNama.getText();
        String nilai = jFieldNilai.getText();
        String gender = "";
        if(btLaki.isSelected()==true){
            gender = btLaki.getText();
        }else if(btPerempuan.isSelected()==true) {
            gender = btPerempuan.getText();
        }
        //System.out.println(nim + nama + nilai + gender);

        listMhs.get(selectedID).setNim(nim);
        listMhs.get(selectedID).setNama(nama);
        listMhs.get(selectedID).setNilai(nilai);
        listMhs.get(selectedID).setGender(gender);
        
        //Update Table
        jTable1.setModel(setTable());

        System.out.println("Update Success!");
        JOptionPane.showMessageDialog(null, "Data berhasil diubah!");

        //reset form         
        resetForm();
    }

    public void deleteData() {
        // delete table
        listMhs.get(selectedID).setNim("");
        listMhs.get(selectedID).setNama("");
        listMhs.get(selectedID).setNilai("");
        listMhs.get(selectedID).setGender("");
        
        int confirm;
        confirm = JOptionPane.showConfirmDialog(this, "Yakin Hapus?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(confirm == JOptionPane.YES_OPTION){
            for (int i = listMhs.size() - 1; i >= 0; i--) {
                if(listMhs.get(i).getNim().equals(""))
                    listMhs.remove(i);
            }
            System.out.println("Delete Success!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            
            //Update Table
            jTable1.setModel(setTable());
            
            //reset form         
            resetForm();
        }else{
            System.out.println("Delete Failed!");
            JOptionPane.showMessageDialog(null, "Data belum berhasil dihapus!");
            
            //reset form         
            resetForm();
        }
    }
    
    public void resetForm() {
        // Set All Value Form to Empty
        jFieldNama.setText("");
        jFieldNIM.setText("");
        jFieldNilai.setText("");
        btLaki.setSelected(false);
        btPerempuan.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jJudul = new javax.swing.JLabel();
        jTombolAdd = new javax.swing.JButton();
        jFieldNIM = new javax.swing.JTextField();
        jLabelNIM = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jFieldNama = new javax.swing.JTextField();
        jLabelNilai = new javax.swing.JLabel();
        jFieldNilai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTombolDelete = new javax.swing.JButton();
        jTombolCancel = new javax.swing.JButton();
        jLabelJur = new javax.swing.JLabel();
        btLaki = new javax.swing.JRadioButton();
        btPerempuan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jJudul.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jJudul.setText("Daftar Mahasiswa");

        jTombolAdd.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTombolAdd.setText("Add");
        jTombolAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTombolAddActionPerformed(evt);
            }
        });

        jFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNIMActionPerformed(evt);
            }
        });

        jLabelNIM.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNIM.setText("NIM");

        jLabelNama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNama.setText("Nama");

        jFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNamaActionPerformed(evt);
            }
        });

        jLabelNilai.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNilai.setText("Nilai");

        jFieldNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNilaiActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Nilai", "Jurusan"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTombolDelete.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTombolDelete.setText("Delete");
        jTombolDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTombolDeleteActionPerformed(evt);
            }
        });

        jTombolCancel.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jTombolCancel.setText("Cancel");
        jTombolCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTombolCancelActionPerformed(evt);
            }
        });

        jLabelJur.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelJur.setText("Jurusan");

        buttonGroup.add(btLaki);
        btLaki.setText("Laki-laki");
        btLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLakiActionPerformed(evt);
            }
        });

        buttonGroup.add(btPerempuan);
        btPerempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btLaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btPerempuan))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jJudul, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabelNIM)
                            .addComponent(jLabelNama)
                            .addComponent(jLabelNilai)
                            .addComponent(jLabelJur))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jTombolDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTombolCancel)
                                    .addComponent(jTombolAdd))
                                .addContainerGap(45, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelNIM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jJudul)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTombolAdd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama)
                    .addComponent(jTombolCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNilai)
                    .addComponent(jTombolDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJur, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLaki)
                    .addComponent(btPerempuan))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNIMActionPerformed

    private void jFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNamaActionPerformed

    private void jFieldNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNilaiActionPerformed

    private void jTombolAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTombolAddActionPerformed
        // TODO add your handling code here:
        
        if (jFieldNama.getText().equals("") || jFieldNIM.getText().equals("") || jFieldNilai.getText().equals("") || btLaki.getText().equals("") || btPerempuan.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Tolong isi Field!");
        else
            if (isUpdate == false)
                insertData();
            else {
                updateData();
                jTombolAdd.setText("Add");
                jTombolDelete.setVisible(false);
                this.isUpdate = false;
                
                //menghilangkan data field setelah di add
                resetForm();
            }
    }//GEN-LAST:event_jTombolAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.isUpdate = true;

        //Get Selected Data
        int row = jTable1.getSelectedRow();
        String selectedNim = (jTable1.getModel().getValueAt(row, 0).toString());
        String selectedNama = (jTable1.getModel().getValueAt(row, 1).toString());
        String selectedNilai = (jTable1.getModel().getValueAt(row, 2).toString());
        String selectedGender = (jTable1.getModel().getValueAt(row, 3).toString());
        
        for (int i = 0; i < listMhs.size(); i++) {
            if (selectedNim.equals(listMhs.get(i).getNim())) {
                selectedID = i;
                break;
            }
        }

        //System.out.println(selectedID);
        jFieldNIM.setText(selectedNim);
        jFieldNama.setText(selectedNama);
        jFieldNilai.setText(selectedNilai);
        if(btLaki.getText() == "Laki-laki"){
            btLaki.setSelected(true);
        }else if(btPerempuan.getText() == "Perempuan") {
            btPerempuan.setSelected(true);
        }

        jTombolAdd.setText("Update");
        jTombolDelete.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTombolDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTombolDeleteActionPerformed
        // TODO add your handling code here:
        if (isUpdate == true) {
            deleteData();
            jTombolAdd.setText("Add");
            jTombolDelete.setVisible(false);
            this.isUpdate = false;
        }
        

    }//GEN-LAST:event_jTombolDeleteActionPerformed

    private void jTombolCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTombolCancelActionPerformed
        // TODO add your handling code here:
        jTombolAdd.setText("Add");
        jTombolDelete.setVisible(false);
        this.isUpdate = false;
        
        //menghilangkan data field setelah di cancel
        resetForm();
    }//GEN-LAST:event_jTombolCancelActionPerformed

    private void btLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLakiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btLaki;
    private javax.swing.JRadioButton btPerempuan;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JTextField jFieldNIM;
    private javax.swing.JTextField jFieldNama;
    private javax.swing.JTextField jFieldNilai;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jLabelJur;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNilai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTombolAdd;
    private javax.swing.JButton jTombolCancel;
    private javax.swing.JButton jTombolDelete;
    // End of variables declaration//GEN-END:variables
}
